server:
  port: 8088

spring:
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: true
  application:
    name: DatingApp
  main:
    allow-bean-definition-overriding: true
  #Email:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kientrungak@gmail.com
    password: hrjp psbp oqce agsq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #multipart
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    #url: jdbc:mysql://datingapp-1.cjgk64oswovm.ap-southeast-2.rds.amazonaws.com:3306/datingapp
    #username: root
    #password: huongntn04
    url: jdbc:mysql://localhost:3306/datingapp
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

firebase:
  storage:
    bucket: gs://datingapp-f4ecb.appspot.com

#########
jwt:
  #secret: kien_key
  expiration: 3600

cloud:
  storage:
    bucket-name: gs://datingapp-f4ecb.appspot.com




#haha
